### ISSUE TITLE
Please implement Thickness

### ISSUE THREAD

**Issue by casainho** [jposada202020/CircuitPython_uplot#7]
The lines on my display are very thin. I wish to have a way to define the Cartesian line to be 2 or 3 pixels thicknes. And then have the same control for the box thickness and ticks.

**Comment by jposada202020** [comment]
Sadly this is not an easy thing to do in the library, if you want to do your whole graphic look bigger you could use something like this:
I just added the possibility for the scale to be chosen by the user. 
Changing the graph thickness would make the library very complex, so that is something that I am not planning to do :)


``` python
plot_1 = Uplot(
    0,
    50,
    100,
    60,
    padding=1,
    show_box=True,
    box_color=color.BLACK,
    background_color=color.WHITE,
    scale=2
)

```

**Comment by casainho** [comment]
Ok, I understand.

I tested the scale but even with big values like 8, I see nothing happening.

**Comment by jposada202020** [comment]
Take a look a the example here https://github.com/jposada202020/CircuitPython_uplot/blob/main/examples/uplot_ufillbetween.py

results:
![image](https://user-images.githubusercontent.com/34255413/224510413-2865d3ac-b015-4952-9fae-412da21e69c1.png)
